# Generated by Django 6.0.1 on 2026-01-29 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('khoi_lop', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('co_so_gan_nhat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.coso')),
            ],
        ),
    ]
