# Generated by Django 6.0.1 on 2026-01-30 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coso',
            options={'verbose_name': 'Cơ sở', 'verbose_name_plural': 'Các cơ sở'},
        ),
        migrations.AlterModelOptions(
            name='hocvien',
            options={'verbose_name': 'Học viên', 'verbose_name_plural': 'Các học viên'},
        ),
        migrations.AddField(
            model_name='coso',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='co_so/', verbose_name='Hình ảnh cơ sở'),
        ),
        migrations.AddField(
            model_name='hocvien',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='hoc_vien/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='coso',
            name='lat',
            field=models.FloatField(verbose_name='Vĩ độ (Lat)'),
        ),
        migrations.AlterField(
            model_name='coso',
            name='lon',
            field=models.FloatField(verbose_name='Kinh độ (Lon)'),
        ),
        migrations.AlterField(
            model_name='coso',
            name='ten',
            field=models.CharField(max_length=200, verbose_name='Tên cơ sở'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='co_so_gan_nhat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.coso', verbose_name='Cơ sở gần nhất'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='khoi_lop',
            field=models.IntegerField(verbose_name='Khối lớp'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='lat',
            field=models.FloatField(verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='lon',
            field=models.FloatField(verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='ten',
            field=models.CharField(max_length=200, verbose_name='Học viên'),
        ),
    ]
