# Generated by Django 6.0.1 on 2026-01-31 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0002_alter_coso_options_alter_hocvien_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hocvien',
            options={},
        ),
        migrations.RemoveField(
            model_name='hocvien',
            name='avatar',
        ),
        migrations.AddField(
            model_name='coso',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hocvien',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coso',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='co_so/'),
        ),
        migrations.AlterField(
            model_name='coso',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coso',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coso',
            name='ten',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='co_so_gan_nhat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.coso'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='khoi_lop',
            field=models.IntegerField(choices=[(6, 'Lớp 6'), (8, 'Lớp 8'), (9, 'Lớp 9')]),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='ten',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mon_day', models.CharField(default='Toán', max_length=50)),
                ('co_so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.coso')),
            ],
        ),
        migrations.CreateModel(
            name='PhongHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('co_so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.coso')),
            ],
        ),
        migrations.CreateModel(
            name='LichHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7'), (8, 'Chủ Nhật')])),
                ('ca', models.IntegerField(choices=[(1, 'Ca 1 (7h30 - 9h00)'), (2, 'Ca 2 (9h30 - 11h00)'), (3, 'Ca 3 (13h30 - 15h00)'), (4, 'Ca 4 (15h30 - 17h00)'), (5, 'Ca 5 (17h30 - 19h00)'), (6, 'Ca 6 (19h30 - 21h00)')])),
                ('giao_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.giaovien')),
                ('hoc_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.hocvien')),
                ('phong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.phonghoc')),
            ],
        ),
    ]
