# Generated by Django 6.0.1 on 2026-01-31 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0003_alter_coso_options_alter_hocvien_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichhoc',
            name='giao_vien',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='hoc_vien',
        ),
        migrations.AddField(
            model_name='phonghoc',
            name='suc_chua',
            field=models.IntegerField(default=30, help_text='Số lượng học viên tối đa'),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='ca',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='thu',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=100)),
                ('si_so_du_kien', models.IntegerField(default=0)),
                ('min_si_so', models.IntegerField(default=20)),
                ('trang_thai', models.CharField(choices=[('CHO', 'Đang chờ (Chưa đủ HS)'), ('MO', 'Đã mở lớp (Sẵn sàng)'), ('HUY', 'Hủy lớp')], default='CHO', max_length=10)),
                ('giao_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.giaovien')),
                ('hoc_viens', models.ManyToManyField(blank=True, to='quan_ly_hoc_vu.hocvien')),
            ],
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='lop_hoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.lophoc'),
        ),
    ]
