# Generated by Django 6.0.1 on 2026-02-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0004_remove_lichhoc_giao_vien_remove_lichhoc_hoc_vien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lophoc',
            name='si_so_du_kien',
        ),
        migrations.AddField(
            model_name='giaovien',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='giao_vien/'),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='si_so_toi_da',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='lop_hoc',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='lich_hoc', to='quan_ly_hoc_vu.lophoc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='phong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.phonghoc'),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='thu',
            field=models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7'), (8, 'Thứ 8')]),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='giao_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.giaovien'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hoc_viens',
            field=models.ManyToManyField(blank=True, related_name='cac_lop_tham_gia', to='quan_ly_hoc_vu.hocvien'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='trang_thai',
            field=models.CharField(choices=[('CHO', 'Sắp mở (Đang tuyển)'), ('MO', 'Đang học (Running)'), ('HUY', 'Đã kết thúc/Hủy')], default='CHO', max_length=10),
        ),
    ]
