# Generated by Django 6.0.1 on 2026-02-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0005_remove_lophoc_si_so_du_kien_giaovien_anh_dai_dien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(default='Học phí tháng ...', max_length=200)),
                ('so_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('CHUA', 'Chưa thanh toán'), ('ROI', 'Đã thanh toán')], default='ROI', max_length=10)),
                ('hoc_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='quan_ly_hoc_vu.hocvien')),
            ],
        ),
    ]
