# Generated by Django 5.2.10 on 2026-03-30 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='co_so/')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mon_day', models.CharField(default='Toán', max_length=50)),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='giao_vien/')),
                ('co_so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.coso')),
            ],
        ),
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True)),
                ('khoi_lop', models.IntegerField(choices=[(6, 'Lớp 6'), (8, 'Lớp 8'), (9, 'Lớp 9')])),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('co_so_gan_nhat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.coso')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(default='Học phí tháng ...', max_length=200)),
                ('so_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('CHUA', 'Chưa thanh toán'), ('ROI', 'Đã thanh toán')], default='ROI', max_length=10)),
                ('hoc_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='quan_ly_hoc_vu.hocvien')),
            ],
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=100)),
                ('si_so_toi_da', models.IntegerField(default=30)),
                ('min_si_so', models.IntegerField(default=20)),
                ('trang_thai', models.CharField(choices=[('CHO', 'Sắp mở (Đang tuyển)'), ('MO', 'Đang học (Running)'), ('HUY', 'Đã kết thúc/Hủy')], default='CHO', max_length=10)),
                ('giao_vien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.giaovien')),
                ('hoc_viens', models.ManyToManyField(blank=True, related_name='cac_lop_tham_gia', to='quan_ly_hoc_vu.hocvien')),
            ],
        ),
        migrations.CreateModel(
            name='PhongHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('suc_chua', models.IntegerField(default=30, help_text='Số lượng học viên tối đa')),
                ('co_so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.coso')),
            ],
        ),
        migrations.CreateModel(
            name='LichHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7'), (8, 'Thứ 8')])),
                ('ca', models.IntegerField()),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hoc', to='quan_ly_hoc_vu.lophoc')),
                ('phong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.phonghoc')),
            ],
        ),
    ]
