# Generated by Django 6.0.3 on 2026-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoa_hoc', models.CharField(max_length=150)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh_anh', models.CharField(blank=True, max_length=500, null=True)),
                ('hoc_phi', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coso',
            name='hinh_anh',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='co_so/'),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='giao_vien/'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='hinh_anh',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='khoi_lop',
            field=models.IntegerField(choices=[(1, 'Lớp 1'), (2, 'Lớp 2'), (3, 'Lớp 3'), (4, 'Lớp 4'), (5, 'Lớp 5'), (6, 'Lớp 6'), (7, 'Lớp 7'), (8, 'Lớp 8'), (9, 'Lớp 9'), (10, 'Lớp 10'), (11, 'Lớp 11'), (12, 'Lớp 12')], default=12),
        ),
    ]
