# Generated by Django 6.0.3 on 2026-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0002_khoahoc_alter_coso_hinh_anh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaovien',
            name='tai_khoan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
