# Generated by Django 6.0.3 on 2026-04-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0003_giaovien_tai_khoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coso',
            name='hinh_anh',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Định dạng file ảnh không hợp lệ.'}, max_length=500, null=True, upload_to='co_so/'),
        ),
        migrations.AlterField(
            model_name='coso',
            name='lat',
            field=models.FloatField(default=0.0, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}),
        ),
        migrations.AlterField(
            model_name='coso',
            name='lon',
            field=models.FloatField(default=0.0, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}),
        ),
        migrations.AlterField(
            model_name='coso',
            name='ten',
            field=models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Định dạng file ảnh không hợp lệ.'}, max_length=500, null=True, upload_to='giao_vien/'),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='co_so',
            field=models.ForeignKey(error_messages={'invalid_choice': 'Lựa chọn của bạn không hợp lệ.', 'null': 'Trường này không được để trống.', 'required': 'Vui lòng chọn một mục từ danh sách.'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.coso'),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='mon_day',
            field=models.CharField(default='Toán', error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='ten',
            field=models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='hoc_vien',
            field=models.ForeignKey(error_messages={'invalid_choice': 'Lựa chọn của bạn không hợp lệ.', 'null': 'Trường này không được để trống.', 'required': 'Vui lòng chọn một mục từ danh sách.'}, on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='quan_ly_hoc_vu.hocvien'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='noi_dung',
            field=models.CharField(default='Học phí tháng ...', error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=200),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='so_tien',
            field=models.DecimalField(decimal_places=0, default=0, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}, max_digits=12),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='trang_thai',
            field=models.CharField(choices=[('CHUA', 'Chưa thanh toán'), ('ROI', 'Đã thanh toán')], default='ROI', error_messages={'invalid_choice': 'Trạng thái thanh toán không hợp lệ.'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='co_so_gan_nhat',
            field=models.ForeignKey(blank=True, error_messages={'invalid_choice': 'Lựa chọn của bạn không hợp lệ.', 'null': 'Trường này không được để trống.', 'required': 'Vui lòng chọn một mục từ danh sách.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.coso'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='hinh_anh',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Định dạng file ảnh không hợp lệ.'}, max_length=500, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='khoi_lop',
            field=models.IntegerField(choices=[(1, 'Lớp 1'), (2, 'Lớp 2'), (3, 'Lớp 3'), (4, 'Lớp 4'), (5, 'Lớp 5'), (6, 'Lớp 6'), (7, 'Lớp 7'), (8, 'Lớp 8'), (9, 'Lớp 9'), (10, 'Lớp 10'), (11, 'Lớp 11'), (12, 'Lớp 12')], default=12, error_messages={'invalid': 'Khối lớp phải là số.', 'invalid_choice': 'Vui lòng chọn khối lớp hợp lệ.'}),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='lat',
            field=models.FloatField(default=0.0, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='lon',
            field=models.FloatField(default=0.0, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='ten',
            field=models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='khoahoc',
            name='hoc_phi',
            field=models.DecimalField(blank=True, decimal_places=0, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='khoahoc',
            name='ten_khoa_hoc',
            field=models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=150),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='ca',
            field=models.IntegerField(error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='lop_hoc',
            field=models.ForeignKey(error_messages={'invalid_choice': 'Lựa chọn của bạn không hợp lệ.', 'null': 'Trường này không được để trống.', 'required': 'Vui lòng chọn một mục từ danh sách.'}, on_delete=django.db.models.deletion.CASCADE, related_name='lich_hoc', to='quan_ly_hoc_vu.lophoc'),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='phong',
            field=models.ForeignKey(error_messages={'invalid_choice': 'Lựa chọn của bạn không hợp lệ.', 'null': 'Trường này không được để trống.', 'required': 'Vui lòng chọn một mục từ danh sách.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.phonghoc'),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='thu',
            field=models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7'), (8, 'Thứ 8')], error_messages={'invalid': 'Thứ phải là một số.', 'invalid_choice': 'Vui lòng chọn ngày trong tuần hợp lệ.'}),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='giao_vien',
            field=models.ForeignKey(error_messages={'invalid_choice': 'Lựa chọn của bạn không hợp lệ.', 'null': 'Trường này không được để trống.', 'required': 'Vui lòng chọn một mục từ danh sách.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.giaovien'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='min_si_so',
            field=models.IntegerField(default=20, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='si_so_toi_da',
            field=models.IntegerField(default=30, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='ten_lop',
            field=models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='trang_thai',
            field=models.CharField(choices=[('CHO', 'Sắp mở (Đang tuyển)'), ('MO', 'Đang học (Running)'), ('HUY', 'Đã kết thúc/Hủy')], default='CHO', error_messages={'invalid_choice': 'Trạng thái lớp không hợp lệ.'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='phonghoc',
            name='co_so',
            field=models.ForeignKey(error_messages={'invalid_choice': 'Lựa chọn của bạn không hợp lệ.', 'null': 'Trường này không được để trống.', 'required': 'Vui lòng chọn một mục từ danh sách.'}, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_hoc_vu.coso'),
        ),
        migrations.AlterField(
            model_name='phonghoc',
            name='suc_chua',
            field=models.IntegerField(default=30, error_messages={'invalid': 'Vui lòng nhập một con số hợp lệ (không chứa chữ cái hay dấu phẩy).', 'max_digits': 'Con số này quá lớn so với giới hạn cho phép.', 'required': 'Vui lòng nhập số liệu.'}, help_text='Số lượng học viên tối đa'),
        ),
        migrations.AlterField(
            model_name='phonghoc',
            name='ten',
            field=models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=50),
        ),
        migrations.CreateModel(
            name='AnhCoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(max_length=500, upload_to='co_so/gallery/')),
                ('thu_tu', models.IntegerField(default=0, help_text='Thứ tự hiển thị (0 = ảnh bìa)')),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
                ('co_so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anh_co_so', to='quan_ly_hoc_vu.coso')),
            ],
            options={
                'ordering': ['thu_tu', 'ngay_them'],
            },
        ),
    ]
