# Generated by Django 6.0.3 on 2026-04-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0004_alter_coso_hinh_anh_alter_coso_lat_alter_coso_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coso',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi nhánh'),
        ),
    ]
