# Generated by Django 6.0.3 on 2026-04-14 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0005_coso_mo_ta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('diem', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5)),
                ('noi_dung', models.TextField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'})),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('duyet', models.BooleanField(default=True)),
                ('co_so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='quan_ly_hoc_vu.coso')),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
