# Generated by Django 6.0.3 on 2026-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0006_danhgia'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='anh_minh_chung',
            field=models.ImageField(blank=True, null=True, upload_to='minh_chung/'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='trang_thai',
            field=models.CharField(choices=[('CHUA', 'Chưa thanh toán'), ('CHO_DUYET', 'Chờ duyệt (Đã gửi ảnh)'), ('ROI', 'Đã thanh toán')], default='CHUA', error_messages={'invalid_choice': 'Trạng thái thanh toán không hợp lệ.'}, max_length=15),
        ),
    ]
