# Generated by Django 6.0.3 on 2026-04-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0007_hoadon_anh_minh_chung_alter_hoadon_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='anh_minh_chung',
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='trang_thai',
            field=models.CharField(choices=[('CHUA', 'Chưa thanh toán'), ('CHO_DUYET', 'Chờ duyệt ảnh'), ('ROI', 'Đã thanh toán')], default='CHUA', max_length=15),
        ),
        migrations.CreateModel(
            name='AnhMinhChung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='minh_chung/')),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True)),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_anh', to='quan_ly_hoc_vu.hoadon')),
            ],
        ),
    ]
