# Generated by Django 6.0.3 on 2026-04-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0008_remove_hoadon_anh_minh_chung_alter_hoadon_trang_thai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='khoa_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_hoc_vu.khoahoc'),
        ),
    ]
