# Generated by Django 6.0.3 on 2026-04-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0009_lophoc_khoa_hoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=200)),
                ('tom_tat', models.TextField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'})),
                ('noi_dung', models.TextField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'})),
                ('hinh_anh', models.ImageField(blank=True, max_length=500, null=True, upload_to='tin_tuc/')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('loai_tin', models.CharField(choices=[('CONG_NGHE', 'Công Nghệ'), ('TUYEN_SINH', 'Tuyển Sinh'), ('HOC_TAP', 'Góc Học Tập')], default='CONG_NGHE', max_length=50)),
            ],
        ),
    ]
