# Generated by Django 6.0.3 on 2026-04-15 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0010_tintuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tintuc',
            name='hinh_anh',
        ),
        migrations.CreateModel(
            name='AnhTinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(max_length=500, upload_to='tin_tuc/')),
                ('tin_tuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_anh', to='quan_ly_hoc_vu.tintuc')),
            ],
        ),
    ]
