# Generated by Django 6.0.3 on 2026-04-15 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0011_remove_tintuc_hinh_anh_anhtintuc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiGiang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=200)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, help_text='Link YouTube', max_length=500, null=True)),
                ('file_bai_tap', models.FileField(blank=True, help_text='File Word/PDF bài tập', null=True, upload_to='bai_tap/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_bai_giang', to='quan_ly_hoc_vu.lophoc')),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
