# Generated by Django 6.0.3 on 2026-04-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0012_baigiang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baigiang',
            name='file_bai_tap',
        ),
        migrations.RemoveField(
            model_name='baigiang',
            name='video_url',
        ),
        migrations.CreateModel(
            name='FileBaiGiang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_dinh_kem', models.FileField(upload_to='bai_tap/')),
                ('bai_giang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_file', to='quan_ly_hoc_vu.baigiang')),
            ],
        ),
        migrations.CreateModel(
            name='VideoBaiGiang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(help_text='Link YouTube', max_length=500)),
                ('bai_giang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_video', to='quan_ly_hoc_vu.baigiang')),
            ],
        ),
    ]
