# Generated by Django 6.0.3 on 2026-04-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0013_remove_baigiang_file_bai_tap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobaigiang',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='bai_giang/videos/'),
        ),
        migrations.AlterField(
            model_name='videobaigiang',
            name='video_url',
            field=models.CharField(blank=True, help_text='Link YouTube', max_length=500, null=True),
        ),
    ]
