# Generated by Django 6.0.3 on 2026-04-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_hoc_vu', '0014_videobaigiang_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(error_messages={'blank': 'Trường này không được để trống.', 'max_length': 'Đoạn văn bản này quá dài so với quy định.', 'required': 'Vui lòng nhập thông tin vào trường này.'}, max_length=200)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('han_nop', models.DateTimeField(blank=True, null=True, verbose_name='Hạn nộp')),
                ('file_de', models.FileField(blank=True, null=True, upload_to='bai_tap/de/', verbose_name='File đề bài')),
                ('hinh_thuc', models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline')], default='ONL', max_length=10)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_tap', to='quan_ly_hoc_vu.lophoc')),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='XinNghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('HV', 'Học viên'), ('GV', 'Giáo viên')], max_length=5)),
                ('ngay_nghi', models.DateField(verbose_name='Ngày xin nghỉ')),
                ('ly_do', models.TextField(verbose_name='Lý do')),
                ('trang_thai', models.CharField(choices=[('CHO', 'Chờ duyệt'), ('DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO', max_length=10)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('giao_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_xin_nghi', to='quan_ly_hoc_vu.giaovien')),
                ('hoc_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_xin_nghi', to='quan_ly_hoc_vu.hocvien')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_xin_nghi', to='quan_ly_hoc_vu.lophoc')),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='LichBu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bu', models.DateField(verbose_name='Ngày dạy bù')),
                ('ca_bu', models.IntegerField(verbose_name='Ca học bù')),
                ('ly_do', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('trang_thai', models.CharField(choices=[('CHO', 'Chờ xác nhận'), ('DUYET', 'Đã lên lịch'), ('HOAN_THANH', 'Đã dạy bù xong'), ('HUY', 'Đã hủy')], default='CHO', max_length=15)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_bu', to='quan_ly_hoc_vu.lophoc')),
                ('xin_nghi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_bu', to='quan_ly_hoc_vu.xinnghi')),
            ],
            options={
                'ordering': ['-ngay_bu'],
            },
        ),
        migrations.CreateModel(
            name='DangKyLichBu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_mat', models.BooleanField(default=True, verbose_name='Có thể tham dự')),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('hoc_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_bu', to='quan_ly_hoc_vu.hocvien')),
                ('lich_bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_dang_ky', to='quan_ly_hoc_vu.lichbu')),
            ],
            options={
                'unique_together': {('hoc_vien', 'lich_bu')},
            },
        ),
        migrations.CreateModel(
            name='NopBaiTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_nop', models.FileField(blank=True, null=True, upload_to='bai_tap/nop/')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú / Giải trình')),
                ('ngay_nop', models.DateTimeField(auto_now_add=True)),
                ('diem', models.FloatField(blank=True, null=True, verbose_name='Điểm số')),
                ('nhan_xet', models.TextField(blank=True, null=True, verbose_name='Nhận xét của GV')),
                ('bai_tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_nop', to='quan_ly_hoc_vu.baitap')),
                ('hoc_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_da_nop', to='quan_ly_hoc_vu.hocvien')),
            ],
            options={
                'unique_together': {('bai_tap', 'hoc_vien')},
            },
        ),
        migrations.CreateModel(
            name='ThoiGianRanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7'), (8, 'Thứ 8')])),
                ('ca', models.IntegerField()),
                ('giao_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoi_gian_ranh', to='quan_ly_hoc_vu.giaovien')),
            ],
            options={
                'ordering': ['thu', 'ca'],
                'unique_together': {('giao_vien', 'thu', 'ca')},
            },
        ),
    ]
